### PR TITLE
Feature aggregation integration

### PR DESCRIPTION
**Pull request by nip5**
The branch I am attempting to merge is a clone of master + your aggregation additions to the feature_OverhaulAggregation branch, bringing feature_OverhaulAggregation up to date. Everything compiles and it passes as many tests as the base master branch does with less warnings.

### CODE REVIEW

**Comment by dschlaep** [comment]
- this is code in early stages of development with demo code full of unresolved merge conflicts, print statements at the global package level, unit tests simply commented out, etc. etc.

- i see nothing that i can contribute at such an early stage of work without specific questions to address

- this is definitely not ready for being merged into master

- have you followed instructions in our guidelines, read our README, and run unit tests locally? if you do, you will see that nothing works. @CaitlinA could you please fill @nip5 in?

**Comment by nip5** [comment]
The 2 unit tests were commented out because they revolve around the downloading information from the internet and this takes so long on my machine that for testing purposes but I will uncomment them because they should do fine on the CIs. I am attempting to merge into feature_Overhaul and NOT into master, the reason behind this is to bring feature_Overhaul up to date with master while also including aggregation changes to the Overhaul branch (which is what my merging branch has implemented).

**Comment by dschlaep** [comment]
> The 2 unit tests were commented out

-> You can and should adjust your local copy for development and debugging, but be careful that you don't push those changes. Unless it is essential for collaboration and well documented that those must be reverted before production ready.
-> I agree that the "unit" tests on this repository are not real unit tests and are taking much too long to be reasonable. Some of the tests are more like "production" tests. However, we are currently lacking a reasonable coverage of unit tests; thus, we have this test project run included to at least attempt to produce consistent results are explicitly describe deviations from earlier output. 

> I am attempting to merge into feature_Overhaul and NOT into master

Correct, sorry, I didn't realize that the target branch was not master. However, I don't see why it can be non-functional and in disarray when merged into any branch.

What's up with the unresolved merge conflicts for instance in the demo code?

What do you want a review for if the CIs are still failing -- without formulating specific questions? Have you looked at any of the CI's output to see what is going on? e.g.
```
Error in setup_aggregations(SFSW2_prj_meta) : 
    There must be at least one aggregating function included in 'agg_funs'
  Error: Test failures
  Execution halted
```

Plus `R CMD check` produces tons of new notes and warnings that don't exist on master -- suggesting that you didn't take care of stuff when merging our newer code, e.g., master, into this branch.

**Comment by nip5** [comment]
I am still getting used to using continuous integration so I did forget to check that it was passing on that, I will be sure to do that in the future. I didn't see any unresolved merge conflicts myself but I will take a closer look.

**Comment by dschlaep** [comment]
OK, thanks!

> unresolved merge conflicts

For instance: lines 75-81 from `demo/SFSW2_project_code.R`
```
<<<<<<< HEAD

SFSW2_prj_meta <- init_rSFSW2_project(
  fmetar = file.path(dir_prj, "SFSW2_project_descriptions.R"), update = FALSE,
  verbose = TRUE, print.debug = FALSE)
=======
fmeta <- file.path(dir_prj, "SFSW2_project_descriptions.rds")
```

**Pull request closed without merging**
